name: Generar Video de Prueba
on:
  workflow_dispatch: # Ejecución manual para pruebas
jobs:
  generar-video:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # Instalar FFmpeg y dependencias
      - name: Instalar FFmpeg y fuentes
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libass-dev fonts-dejavu-core fonts-ubuntu jq

      # Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Instalar dependencias de Python
      - name: Instalar dependencias
        run: pip install gTTS google-generativeai openai-whisper requests

      # Descargar imagen (Unsplash o Pexels)
      - name: Descargar imagen
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            curl -o imagen.jpg "https://source.unsplash.com/random/1920x1080/?nature" || echo "Error descargando de Unsplash"
          else
            curl -H "Authorization: ${{ secrets.PEXELS_API_KEY }}" -o imagen.jpg "https://api.pexels.com/v1/search?query=nature&per_page=1" | jq -r '.photos[0].src.original' || echo "Error descargando de Pexels"
          fi
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

      # Generar guión con Gemini
      - name: Generar guión
        run: python generate_script.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # Generar voz en off
      - name: Generar voz en off
        run: python generate_voice.py

      # Descargar música
      - name: Descargar música
        run: curl -o musica.mp3 "https://www.youtube.com/audiolibrary_download?vid=example" || echo "Error descargando música" # Reemplaza con enlace válido

      # Generar subtítulos
      - name: Generar subtítulos
        run: python generate_subtitles.py

      # Verificar archivos
      - name: Verificar archivos
        run: |
          ls -la imagen.jpg audio.mp3 musica.mp3 subtitulos.srt || echo "Falta algún archivo"
          file imagen.jpg audio.mp3 musica.mp3 subtitulos.srt || echo "Error en archivos"

      # Generar video
      - name: Generar video
        run: |
          ffmpeg -loop 1 -i imagen.jpg -i audio.mp3 -i musica.mp3 -vf "subtitles=subtitulos.srt:force_style='Fontsize=24,PrimaryColour=&Hffffff'" -c:v libx264 -c:a aac -filter_complex "[1:a][2:a]amix=inputs=2:duration=longest" -t 60 -pix_fmt yuv420p -shortest output.mp4 2> ffmpeg_error.log
          cat ffmpeg_error.log

      # Subir resultados
      - name: Subir resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultados
          path: |
            output.mp4
            imagen.jpg
            audio.mp3
            musica.mp3
            subtitulos.srt
            ffmpeg_error.log
