name: Generar y Subir Video YouTube
on:
  schedule:
    - cron: '0 12 * * 1-5' # Lunes a viernes a las 12:00 UTC
  workflow_dispatch: # Permite ejecución manual para pruebas
jobs:
  generar-video:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # Instalar FFmpeg
      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Instalar dependencias de Python
      - name: Instalar dependencias
        run: pip install gTTS google-api-python-client google-auth-oauthlib openai-whisper

      # Descargar imagen automáticamente (Unsplash)
      - name: Descargar imagen
        run: curl -o imagen.jpg "https://source.unsplash.com/random/1920x1080/?nature"

      # Generar voz en off
      - name: Generar voz en off
        run: python generate_voice.py
        env:
          VIDEO_TOPIC: "Naturaleza" # Cambia según el tema de tu canal

      # Descargar música de fondo
      - name: Descargar música
        run: curl -o musica.mp3 "https://www.youtube.com/audiolibrary_download?vid=example" # Reemplaza con un enlace válido

      # Generar subtítulos
      - name: Generar subtítulos
        run: python generate_subtitles.py

      # Generar video con FFmpeg
      - name: Generar video
        run: |
          ffmpeg -loop 1 -i imagen.jpg -i audio.mp3 -i musica.mp3 -vf "subtitles=subtitulos.srt:force_style='FontSize=24,PrimaryColour=&Hffffff&'" -c:v libx264 -c:a aac -filter_complex "[1:a][2:a]amix=inputs=2:duration=longest" -t 1200 -pix_fmt yuv420p -shortest output.mp4 2> ffmpeg_error.log
          cat ffmpeg_error.log # Mostrar errores para depuración

      # Subir video a YouTube
      - name: Subir a YouTube
        run: python upload_video.py
        env:
          CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS }}
